#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Creates an External source. ExtSource name and type are required fields.
	--------------------------------------
	Available options:
	--extSourceName   | -e extSrouce name
	--extSourceType   | -t type (KERBEROS/IDP/INTERNAL/SQL/LDAP/ISMU/X509)
	--batch           | -b batch
	--help            | -h prints this help

	};
}

my ($extSourceName, $extSourceType, $batch);
GetOptions ("help|h"    => sub {
		print help();
		exit 0;
	}, "batch|b"        => \$batch,
	"extSourceName|e=s" => \$extSourceName, "extSourceType|t=s" => \$extSourceType) || die help();

# Check options
unless (defined($extSourceName)) { die "ERROR: extSourceName is required \n";}
unless (defined($extSourceType)) { die "ERROR: extSourceType is required \n";}
unless ($extSourceName !~ /^\s*$/) { die "ERROR: extSourceName cannot be empty string\n";}
unless ($extSourceType !~ /^\s*$/) { die "ERROR: extSourceType cannot be empty string\n";}

# Convert type
my %extSourceMapper = (
	"KERBEROS" => "cz.metacentrum.perun.core.impl.ExtSourceKerberos",
	"IDP" => "cz.metacentrum.perun.core.impl.ExtSourceIdp",
	"INTERNAL" => "cz.metacentrum.perun.core.impl.ExtSourceInternal",
	"LDAP" => "cz.metacentrum.perun.core.impl.ExtSourceLdap",
	"ISMU" => "cz.metacentrum.perun.core.impl.ExtSourceISMU",
	"SQL" => "cz.metacentrum.perun.core.impl.ExtSourceSql",
	"X509" => "cz.metacentrum.perun.core.impl.ExtSourceX509"
);

my $extSourceTypeInternal = $extSourceMapper{$extSourceType};

my $agent = Perun::Agent->new();
my $extSourceAgent = $agent->getExtSourcesAgent;

my $extSource = Perun::beans::ExtSource->new;
$extSource->setName( $extSourceName );
$extSource->setType( $extSourceTypeInternal );

$extSource = $extSourceAgent->createExtSource( extSource => $extSource );

printMessage("ExtSource Id:".$extSource->getId." successfully created", $batch);
