#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Creates a securityTeam. SecurityTeam name is required field.
	--------------------------------------
	Available options:
	--securityTeamName | -S securityTeam name (no space allowed)
	--description      | -d description
	--batch            | -b batch
	--help             | -h prints this help

	};
}

my ($securityTeamName, $desc, $batch);
GetOptions ("help|h"       => sub {
		print help();
		exit 0;
	}, "batch|b"           => \$batch,
	"securityTeamName|S=s" => \$securityTeamName,
	"description|d=s"      => \$desc || die help());

# Check options
unless (defined($securityTeamName)) { die "ERROR: securityTeamName is required \n";}
if ($securityTeamName =~ /\W/) { die "ERROR: securityTeamName has wrong format \n";}

my $agent = Perun::Agent->new();
my $securityTeamsAgent = $agent->getSecurityTeamsAgent;

my $securityTeam = Perun::beans::SecurityTeam->new;
$securityTeam->setName( $securityTeamName );
$securityTeam->setDescription( $desc ) if (defined($desc));

$securityTeam = $securityTeamsAgent->createSecurityTeam( securityTeam => $securityTeam );

printMessage("SecurityTeam Id:".$securityTeam->getId." successfully created", $batch);
