#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Text::ASCIITable;
use Perun::Agent;
use Perun::Common qw(printMessage printTable getSortingFunction);

sub help {
	return qq{
	Lists Specific users assigned to User. User id is required.
	--------------------------------------
	Available options:
	--userId       | -u user id
	--batch        | -b batch
	--help         | -h prints this help

	};
}

my ($userId, $ownerId, $batch);
GetOptions ("help|h"  => sub {
		print help();
		exit 0;
	}, "batch|b"        => \$batch,
	"userId|u=i"        => \$userId ) || die help();

# Check options
unless (defined($userId)) { die "ERROR: userId is required \n";}

my $agent = Perun::Agent->new();
my $usersAgent = $agent->getUsersAgent;

my @users=$usersAgent->getSpecificUsersByUser( user => $userId );
unless (@users) {
	printMessage "No users found", $batch;
	exit 0;
}


#output
my $sortingFunction = getSortingFunction("getSortingName", 1);
printTable($sortingFunction, @users);
