#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Text::ASCIITable;
use Perun::Agent;
use Perun::Common qw(printMessage tableToPrint getSortingFunction);

sub help {
	return qq{
	Lists Sponsors assigned to Member
	--------------------------------------
	Available options:
	--memberId       | -m member id
	--batch          | -b batch
	--help           | -h prints this help
	};
}

my ($memberId, $batch);
GetOptions ("help|h"  => sub {
		print help();
		exit 0;
	}, "batch|b"        => \$batch,
	"memberId|m=i"        => \$memberId ) || die help();

# Check options
unless (defined($memberId)) { die "ERROR: memberId is required \n";}

my $agent = Perun::Agent->new();
my $usersAgent = $agent->getUsersAgent;

my @sponsors=$usersAgent->getSponsorsForMember(member => $memberId );
unless (@sponsors) {
	printMessage "No sponsor found", $batch;
	exit 0;
}

#output
my $table = Text::ASCIITable->new( { reportErrors => 0, utf8 => 0 } );
$table->setCols( 'ID', 'Name' );

foreach my $sponsor (@sponsors) {
	$table->addRow( $sponsor->getUserId, $sponsor->getUserFirstName.' '.$sponsor->getUserLastName );
}

print tableToPrint($table, $batch);

