#!/usr/bin/perl

use strict;
use warnings;
use YAML::XS qw'DumpFile LoadFile';
use File::Basename;

my $homedir = $ENV{HOME};
my $filename = ".perun_token";

#if token file does not exist, token needs to be obtained and saved
unless (-e $homedir . "/" . $filename) {

	#/get access token/ and save refresh token:
	my %data = (
		refresh_token => 'my_example_refresh_token',
		expires_at        => time() #if getting expiration from library, set value here, otherwise add expiration time to current time
		# (now using epoch, might want to use different format)
	);

	DumpFile($homedir . '/' . $filename, \%data);

} else {
	#load token file and check validity
	my $tokenData = LoadFile($homedir . "/" . $filename);

	#/use token if it won't expire during script execution/ = probably want to add a few minutes to the expiration
	if (time() > $tokenData->{"expires_at"}) {
		print "Token expired\n"
	} else {
		#/use refresh token to get access token/
		print $tokenData->{"refresh_token"};
	}
}

