#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;

sub help {
	return qq{
	Reloads existing configurations of branding and their respective apps as configured in perun-apps-config.yml
	------------------------------

};
}

GetOptions ("help|h"    => sub {
	print help();
	exit 0;
}) || die help();

my $agent = Perun::Agent->new();

my $configAgent = $agent->getConfigAgent;

$configAgent->reloadAppsConfig;
