#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Removes all attributes from the user and facility. Facility id or name and user id are required.
	--------------------------------------------------
	Available options:
	--facilityId   | -f facility id
	--facilityName | -F facility name
	--userId       | -u user id
	--batch        | -b batch
	--help         | -h prints this help

	};
}

my ($facilityId, $facilityName, $userId, $batch);
GetOptions ("help|h"   => sub {
		print help();
		exit 0;
	}, "batch|b"       => \$batch,
	"facilityId|f=i"   => \$facilityId,
	"facilityName|F=s" => \$facilityName,
	"userId|u=i"       => \$userId) || die help();

# Check options
unless (defined($facilityId) or (defined($facilityName))) { die "ERROR: facilityId or facilityName is required \n";}
unless (defined($userId)) { die "ERROR: userId is required \n";}

my $agent = Perun::Agent->new();
unless ($facilityId) {
	my $facilitiesAgent = $agent->getFacilitiesAgent;
	my $facility = $facilitiesAgent->getFacilityByName( name => $facilityName );
	$facilityId = $facility->getId;
}

my $attributesAgent = $agent->getAttributesAgent;

$attributesAgent->removeAllAttributes( facility => $facilityId, user => $userId );

printMessage("All attributes removed from the user Id: $userId and the facility Id: $facilityId", $batch);
