#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Sets sponsorship for member. Member ID and sponsor ID is required.
	--------------------------------------
	Available options:
	--memberId       | -m member id
	--sponsorId      | -s sponsor (user) id
	--batch          | -b batch
	--help           | -h prints this help
	};
}

my ($memberId, $sponsorId, $batch);
GetOptions ("help|h"  => sub {
		print help();
		exit 0;
	}, "batch|b"        => \$batch,
	"memberId|m=i"        => \$memberId, 
	"sponsorId|s=i"         => \$sponsorId ) || die help();

# Check options
unless (defined($memberId)) { die "ERROR: memberId is required \n";}
unless (defined($sponsorId)) { die "ERROR: sponsorId is required \n";}

my $agent = Perun::Agent->new();
my $membersAgent = $agent->getMembersAgent;

$membersAgent->setSponsorshipForMember( sponsoredMember => $memberId, sponsor => $sponsorId );

printMessage("Member Id:$memberId was successfully set as sponsored by user Id:$sponsorId.", $batch);
