package cz.metacentrum.perun.webgui.client.resources;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.ConstantsWithLookup;

/**
 * Interface for attributes names and descriptions
 * Do not edit this file manually, generate it with script from the result of "attributesManager/getAttributesDefinition"
 * 
 * @author Vaclav Mach <374430@mail.muni.cz>
 * @version $Id$
 */
public interface AttributesConstants extends ConstantsWithLookup {
	
	public static final AttributesConstants INSTANCE = GWT.create(AttributesConstants.class);

    @DefaultStringValue("Login in")
    String urn_perun_user_attribute_def_def_login_namespace_name();

    @DefaultStringValue("Login in namespace")
    String urn_perun_user_attribute_def_def_login_namespace_description();

    @DefaultStringValue("UID in")
    String urn_perun_user_attribute_def_def_uid_namespace_name();

    @DefaultStringValue("UID in namespace")
    String urn_perun_user_attribute_def_def_uid_namespace_description();

    @DefaultStringValue("Unix group name in")
    String urn_perun_group_attribute_def_def_unixGroupName_namespace_name();

    @DefaultStringValue("Unix group name in namespace")
    String urn_perun_group_attribute_def_def_unixGroupName_namespace_description();

    @DefaultStringValue("Unix group name in")
    String urn_perun_resource_attribute_def_def_unixGroupName_namespace_name();

    @DefaultStringValue("Unix group name in namespace")
    String urn_perun_resource_attribute_def_def_unixGroupName_namespace_description();

    @DefaultStringValue("Unix GID in")
    String urn_perun_group_attribute_def_def_unixGID_namespace_name();

    @DefaultStringValue("Unix GID in namespace")
    String urn_perun_group_attribute_def_def_unixGID_namespace_description();

    @DefaultStringValue("Unix GID in")
    String urn_perun_resource_attribute_def_def_unixGID_namespace_name();

    @DefaultStringValue("Unix GID in namespace")
    String urn_perun_resource_attribute_def_def_unixGID_namespace_description();

    // FIXME - constant interface can't pass parameters ??
    @DefaultStringValue("Used when whole Resource is group on Facility.")
    String when_resource_is_group_on_facility();

    @DefaultStringValue("shells")
    String urn_perun_facility_attribute_def_def_shells_name();

    @DefaultStringValue("Available shells")
    String urn_perun_facility_attribute_def_def_shells_description();

    @DefaultStringValue("name")
    String urn_perun_facility_attribute_def_core_name_name();

    @DefaultStringValue("facility.name")
    String urn_perun_facility_attribute_def_core_name_description();

    @DefaultStringValue("homeMountPoints")
    String urn_perun_facility_attribute_def_def_homeMountPoints_name();

    @DefaultStringValue("Available mount points for home")
    String urn_perun_facility_attribute_def_def_homeMountPoints_description();

    @DefaultStringValue("Unix groups namespace (do not use)")
    String urn_perun_facility_attribute_def_def_unixGroup_namespace_name();

    @DefaultStringValue("This attribute is not used anymore! Please use Unix group name namespace attribute.")
    String urn_perun_facility_attribute_def_def_unixGroup_namespace_description();

    @DefaultStringValue("Unix group name namespace")
    String urn_perun_facility_attribute_def_def_unixGroupName_namespace_name();

    @DefaultStringValue("Define namespace for unix groups names on Facility.")
    String urn_perun_facility_attribute_def_def_unixGroupName_namespace_description();

    @DefaultStringValue("KERBEROS principals")
    String urn_perun_user_attribute_def_def_kerberosLogins_name();

    @DefaultStringValue("Logins in KERBEROS (including realm).")
    String urn_perun_user_attribute_def_def_kerberosLogins_description();

    @DefaultStringValue("KERBEROS principals (Full)")
    String urn_perun_user_attribute_def_virt_kerberosLogins_name();

    @DefaultStringValue("Logins in KERBEROS (including realm and kerberos UserExtSources).")
    String urn_perun_user_attribute_def_virt_kerberosLogins_description();

    @DefaultStringValue("smb_conf_path")
    String urn_perun_facility_attribute_def_def_smb_conf_path_name();

    @DefaultStringValue("path to Samba configuration files")
    String urn_perun_facility_attribute_def_def_smb_conf_path_description();

    @DefaultStringValue("smb_share_path")
    String urn_perun_facility_attribute_def_def_smb_share_path_name();

    @DefaultStringValue("root path to all Samba shares")
    String urn_perun_facility_attribute_def_def_smb_share_path_description();

    @DefaultStringValue("defaultShell")
    String urn_perun_resource_attribute_def_def_defaultShell_name();

    @DefaultStringValue("Default shell for members")
    String urn_perun_resource_attribute_def_def_defaultShell_description();

    @DefaultStringValue("shells")
    String urn_perun_resource_attribute_def_def_shells_name();

    @DefaultStringValue("Available shells")
    String urn_perun_resource_attribute_def_def_shells_description();

    @DefaultStringValue("homeMountPoints")
    String urn_perun_resource_attribute_def_def_homeMountPoints_name();

    @DefaultStringValue("Available mount points for home")
    String urn_perun_resource_attribute_def_def_homeMountPoints_description();

    @DefaultStringValue("ID")
    String urn_perun_member_attribute_def_core_id_name();

    @DefaultStringValue("ID of Member in VO.")
    String urn_perun_member_attribute_def_core_id_description();

    @DefaultStringValue("shell")
    String urn_perun_user_facility_attribute_def_def_shell_name();

    @DefaultStringValue("Shell")
    String urn_perun_user_facility_attribute_def_def_shell_description();

    @DefaultStringValue("homeMountPoint")
    String urn_perun_user_facility_attribute_def_def_homeMountPoint_name();

    @DefaultStringValue("homeMountPoint")
    String urn_perun_user_facility_attribute_def_def_homeMountPoint_description();

    @DefaultStringValue("defaultHomeMountPoint")
    String urn_perun_resource_attribute_def_def_defaultHomeMountPoint_name();

    @DefaultStringValue("Default mount point for members")
    String urn_perun_resource_attribute_def_def_defaultHomeMountPoint_description();

    @DefaultStringValue("smb_write_conf")
    String urn_perun_facility_attribute_def_def_smb_write_conf_name();

    @DefaultStringValue("automatically update Samba config files")
    String urn_perun_facility_attribute_def_def_smb_write_conf_description();

    @DefaultStringValue("id")
    String urn_perun_resource_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_core_id_description();

    @DefaultStringValue("name")
    String urn_perun_resource_attribute_def_core_name_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_core_name_description();

    @DefaultStringValue("description")
    String urn_perun_resource_attribute_def_core_description_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_core_description_description();

    @DefaultStringValue("id")
    String urn_perun_facility_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_core_id_description();

    @DefaultStringValue("type")
    String urn_perun_facility_attribute_def_core_type_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_core_type_description();

    @DefaultStringValue("id")
    String urn_perun_vo_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_vo_attribute_def_core_id_description();

    @DefaultStringValue("name")
    String urn_perun_vo_attribute_def_core_name_name();

    @DefaultStringValue("")
    String urn_perun_vo_attribute_def_core_name_description();

    @DefaultStringValue("shortName")
    String urn_perun_vo_attribute_def_core_shortName_name();

    @DefaultStringValue("")
    String urn_perun_vo_attribute_def_core_shortName_description();

    @DefaultStringValue("id")
    String urn_perun_user_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_id_description();

    @DefaultStringValue("firstName")
    String urn_perun_user_attribute_def_core_firstName_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_firstName_description();

    @DefaultStringValue("lastName")
    String urn_perun_user_attribute_def_core_lastName_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_lastName_description();

    @DefaultStringValue("middleName")
    String urn_perun_user_attribute_def_core_middleName_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_middleName_description();

    @DefaultStringValue("titleBefore")
    String urn_perun_user_attribute_def_core_titleBefore_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_titleBefore_description();

    @DefaultStringValue("titleAfter")
    String urn_perun_user_attribute_def_core_titleAfter_name();

    @DefaultStringValue("")
    String urn_perun_user_attribute_def_core_titleAfter_description();

    @DefaultStringValue("accountExpirationTime")
    String urn_perun_user_facility_attribute_def_def_accountExpirationTime_name();

    @DefaultStringValue("account expiration")
    String urn_perun_user_facility_attribute_def_def_accountExpirationTime_description();

    @DefaultStringValue("adobeConnectRoom")
    String urn_perun_resource_attribute_def_def_adobeConnectRoom_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_def_adobeConnectRoom_description();

    @DefaultStringValue("UID")
    String urn_perun_user_facility_attribute_def_virt_UID_name();

    @DefaultStringValue("")
    String urn_perun_user_facility_attribute_def_virt_UID_description();

    @DefaultStringValue("uid-namespace")
    String urn_perun_facility_attribute_def_def_uid_namespace_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_uid_namespace_description();

    @DefaultStringValue("unixGID-namespace")
    String urn_perun_facility_attribute_def_def_unixGID_namespace_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_unixGID_namespace_description();

    @DefaultStringValue("groupExtSource")
    String urn_perun_group_attribute_def_def_groupExtSource_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_def_groupExtSource_description();

    @DefaultStringValue("groupMembersExtSource")
    String urn_perun_group_attribute_def_def_groupMembersExtSource_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_def_groupMembersExtSource_description();

    @DefaultStringValue("groupMembersQuery")
    String urn_perun_group_attribute_def_def_groupMembersQuery_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_def_groupMembersQuery_description();

    @DefaultStringValue("synchronizationEnabled")
    String urn_perun_group_attribute_def_def_synchronizationEnabled_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_def_synchronizationEnabled_description();

    @DefaultStringValue("synchronizationInterval")
    String urn_perun_group_attribute_def_def_synchronizationInterval_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_def_synchronizationInterval_description();

    @DefaultStringValue("namespace-minUID")
    String urn_perun_entityless_attribute_def_def_namespace_minUID_name();

    @DefaultStringValue("")
    String urn_perun_entityless_attribute_def_def_namespace_minUID_description();

    @DefaultStringValue("namespace-maxUID")
    String urn_perun_entityless_attribute_def_def_namespace_maxUID_name();

    @DefaultStringValue("")
    String urn_perun_entityless_attribute_def_def_namespace_maxUID_description();

    @DefaultStringValue("namespace-minGID")
    String urn_perun_entityless_attribute_def_def_namespace_minGID_name();

    @DefaultStringValue("")
    String urn_perun_entityless_attribute_def_def_namespace_minGID_description();

    @DefaultStringValue("namespace-maxGID")
    String urn_perun_entityless_attribute_def_def_namespace_maxGID_name();

    @DefaultStringValue("")
    String urn_perun_entityless_attribute_def_def_namespace_maxGID_description();

    @DefaultStringValue("smb_share_name")
    String urn_perun_group_resource_attribute_def_def_smb_share_name_name();

    @DefaultStringValue("name of Samba share created by group")
    String urn_perun_group_resource_attribute_def_def_smb_share_name_description();

    @DefaultStringValue("workplace")
    String urn_perun_member_attribute_def_def_workplace_name();

    @DefaultStringValue("Workplace under the user's organization")
    String urn_perun_member_attribute_def_def_workplace_description();

    @DefaultStringValue("hostName")
    String urn_perun_facility_attribute_def_def_hostName_name();

    @DefaultStringValue("zkracene jmeno stroje")
    String urn_perun_facility_attribute_def_def_hostName_description();

    @DefaultStringValue("hostCoresNumber")
    String urn_perun_facility_attribute_def_def_hostCoresNumber_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_hostCoresNumber_description();

    @DefaultStringValue("smb_groupshare")
    String urn_perun_resource_attribute_def_def_smb_groupshare_name();

    @DefaultStringValue("groups on resource represents Samba shares")
    String urn_perun_resource_attribute_def_def_smb_groupshare_description();

    @DefaultStringValue("coresNumber")
    String urn_perun_host_attribute_def_def_coresNumber_name();

    @DefaultStringValue("")
    String urn_perun_host_attribute_def_def_coresNumber_description();

    @DefaultStringValue("fsHomeMountPoint")
    String urn_perun_resource_attribute_def_def_fsHomeMountPoint_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_def_fsHomeMountPoint_description();

    @DefaultStringValue("defaultDataLimit")
    String urn_perun_resource_attribute_def_def_defaultDataLimit_name();

    @DefaultStringValue("Hard quota including units (M,G,T, ...), G is default.")
    String urn_perun_resource_attribute_def_def_defaultDataLimit_description();

    @DefaultStringValue("defaultDataQuota")
    String urn_perun_resource_attribute_def_def_defaultDataQuota_name();

    @DefaultStringValue("Soft quota including units (M, G, T, ...), G is default")
    String urn_perun_resource_attribute_def_def_defaultDataQuota_description();

    @DefaultStringValue("shell_passwd-scp")
    String urn_perun_facility_attribute_def_def_shell_passwd_scp_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_shell_passwd_scp_description();

    @DefaultStringValue("kerberosAdminPrincipal")
    String urn_perun_user_attribute_def_def_kerberosAdminPrincipal_name();

    @DefaultStringValue("Kerberos pricipal used for root access (user).")
    String urn_perun_user_attribute_def_def_kerberosAdminPrincipal_description();

    @DefaultStringValue("defaultFilesQuota")
    String urn_perun_resource_attribute_def_def_defaultFilesQuota_name();

    @DefaultStringValue("Soft quota for number of files")
    String urn_perun_resource_attribute_def_def_defaultFilesQuota_description();

    @DefaultStringValue("defaultFilesLimit")
    String urn_perun_resource_attribute_def_def_defaultFilesLimit_name();

    @DefaultStringValue("Hard quota for number of files")
    String urn_perun_resource_attribute_def_def_defaultFilesLimit_description();

    @DefaultStringValue("Membership expiration")
    String urn_perun_member_attribute_def_def_membershipExpiration_name();

    @DefaultStringValue("Date of VO membership expiration.")
    String urn_perun_member_attribute_def_def_membershipExpiration_description();

    @DefaultStringValue("sponzoredMember")
    String urn_perun_member_attribute_def_def_sponzoredMember_name();

    @DefaultStringValue("RT ticket number, which describes why the member's membership is sponzored")
    String urn_perun_member_attribute_def_def_sponzoredMember_description();

    @DefaultStringValue("smb_group_is_share")
    String urn_perun_group_resource_attribute_def_def_smb_group_is_share_name();

    @DefaultStringValue("group creates it's own share on Samba server")
    String urn_perun_group_resource_attribute_def_def_smb_group_is_share_description();

    @DefaultStringValue("smb_write_group")
    String urn_perun_group_resource_attribute_def_def_smb_write_group_name();

    @DefaultStringValue("is group share writeable")
    String urn_perun_group_resource_attribute_def_def_smb_write_group_description();

    @DefaultStringValue("smb_username")
    String urn_perun_member_attribute_def_def_smb_username_name();

    @DefaultStringValue("username used for logging to Samba")
    String urn_perun_member_attribute_def_def_smb_username_description();

    @DefaultStringValue("displayName")
    String urn_perun_user_attribute_def_core_displayName_name();

    @DefaultStringValue("User's display name")
    String urn_perun_user_attribute_def_core_displayName_description();

    @DefaultStringValue("isSystemUnixGroup")
    String urn_perun_group_resource_attribute_def_def_isSystemUnixGroup_name();

    @DefaultStringValue("The group is system unix group")
    String urn_perun_group_resource_attribute_def_def_isSystemUnixGroup_description();

    @DefaultStringValue("systemUnixGID")
    String urn_perun_group_resource_attribute_def_def_systemUnixGID_name();

    @DefaultStringValue("GID of the system unix group")
    String urn_perun_group_resource_attribute_def_def_systemUnixGID_description();

    @DefaultStringValue("systemUnixGroupName")
    String urn_perun_group_resource_attribute_def_def_systemUnixGroupName_name();

    @DefaultStringValue("Name of the system unix group")
    String urn_perun_group_resource_attribute_def_def_systemUnixGroupName_description();

    @DefaultStringValue("homeDirUmask")
    String urn_perun_facility_attribute_def_def_homeDirUmask_name();

    @DefaultStringValue("Unix umask to be set on each created home directory")
    String urn_perun_facility_attribute_def_def_homeDirUmask_description();

    @DefaultStringValue("id")
    String urn_perun_group_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_core_id_description();

    @DefaultStringValue("name")
    String urn_perun_group_attribute_def_core_name_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_core_name_description();

    @DefaultStringValue("description")
    String urn_perun_group_attribute_def_core_description_name();

    @DefaultStringValue("")
    String urn_perun_group_attribute_def_core_description_description();

    @DefaultStringValue("unixGroupName")
    String urn_perun_resource_attribute_def_def_unixGroupName_name();

    @DefaultStringValue("defaultni unixova skupina pro resource")
    String urn_perun_resource_attribute_def_def_unixGroupName_description();

    @DefaultStringValue("login")
    String urn_perun_user_facility_attribute_def_virt_login_name();

    @DefaultStringValue("")
    String urn_perun_user_facility_attribute_def_virt_login_description();

    @DefaultStringValue("login-namespace")
    String urn_perun_facility_attribute_def_def_login_namespace_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_login_namespace_description();

    @DefaultStringValue("maxGID")
    String urn_perun_facility_attribute_def_virt_maxGID_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_virt_maxGID_description();

    @DefaultStringValue("maxUID")
    String urn_perun_facility_attribute_def_virt_maxUID_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_virt_maxUID_description();

    @DefaultStringValue("minUID")
    String urn_perun_facility_attribute_def_virt_minUID_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_virt_minUID_description();

    @DefaultStringValue("minGID")
    String urn_perun_facility_attribute_def_virt_minGID_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_virt_minGID_description();

    @DefaultStringValue("fsScratchMountPoint")
    String urn_perun_facility_attribute_def_def_fsScratchMountPoint_name();

    @DefaultStringValue("Mountpoint where the scratch is located")
    String urn_perun_facility_attribute_def_def_fsScratchMountPoint_description();

    @DefaultStringValue("homeMountPoint_passwd-scp")
    String urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scp_name();

    @DefaultStringValue("")
    String urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scp_description();

    @DefaultStringValue("status")
    String urn_perun_member_attribute_def_core_status_name();

    @DefaultStringValue("membership status (valid,invalid,disabled,suspended,expired)")
    String urn_perun_member_attribute_def_core_status_description();

    @DefaultStringValue("passwdScpDestinationFile")
    String urn_perun_facility_attribute_def_def_passwdScpDestinationFile_name();

    @DefaultStringValue("Path where passwd file (for passwd_scp service) is stored. (Typicaly: /etc/passwd)")
    String urn_perun_facility_attribute_def_def_passwdScpDestinationFile_description();

    @DefaultStringValue("registrationNote")
    String urn_perun_member_attribute_def_opt_registrationNote_name();

    @DefaultStringValue("Note entered on the registration page")
    String urn_perun_member_attribute_def_opt_registrationNote_description();

    @DefaultStringValue("dataQuota")
    String urn_perun_member_resource_attribute_def_def_dataQuota_name();

    @DefaultStringValue("Soft quota including units (M, G, T, ...), G is default")
    String urn_perun_member_resource_attribute_def_def_dataQuota_description();

    @DefaultStringValue("filesQuota")
    String urn_perun_member_resource_attribute_def_def_filesQuota_name();

    @DefaultStringValue("Soft quota for number of files")
    String urn_perun_member_resource_attribute_def_def_filesQuota_description();

    @DefaultStringValue("dataLimit")
    String urn_perun_member_resource_attribute_def_def_dataLimit_name();

    @DefaultStringValue("Hard quota including units (M, G, T, ...), G is default")
    String urn_perun_member_resource_attribute_def_def_dataLimit_description();

    @DefaultStringValue("filesLimit")
    String urn_perun_member_resource_attribute_def_def_filesLimit_name();

    @DefaultStringValue("Hard quota for number of files")
    String urn_perun_member_resource_attribute_def_def_filesLimit_description();

    @DefaultStringValue("preferredLanguage")
    String urn_perun_member_attribute_def_def_preferredLanguage_name();

    @DefaultStringValue("Language which user preferres for communication")
    String urn_perun_member_attribute_def_def_preferredLanguage_description();

    @DefaultStringValue("mail")
    String urn_perun_member_attribute_def_def_mail_name();

    @DefaultStringValue("")
    String urn_perun_member_attribute_def_def_mail_description();

    @DefaultStringValue("address")
    String urn_perun_member_attribute_def_def_address_name();

    @DefaultStringValue("")
    String urn_perun_member_attribute_def_def_address_description();

    @DefaultStringValue("id")
    String urn_perun_host_attribute_def_core_id_name();

    @DefaultStringValue("")
    String urn_perun_host_attribute_def_core_id_description();

    @DefaultStringValue("hostname")
    String urn_perun_host_attribute_def_core_hostname_name();

    @DefaultStringValue("")
    String urn_perun_host_attribute_def_core_hostname_description();

    @DefaultStringValue("phone")
    String urn_perun_member_attribute_def_def_phone_name();

    @DefaultStringValue("Phone")
    String urn_perun_member_attribute_def_def_phone_description();

    @DefaultStringValue("organization")
    String urn_perun_member_attribute_def_def_organization_name();

    @DefaultStringValue("Organization")
    String urn_perun_member_attribute_def_def_organization_description();

    @DefaultStringValue("perunPeopleId")
    String urn_perun_user_attribute_def_opt_perunPeopleId_name();

    @DefaultStringValue("Id of the users in the old Perun DB")
    String urn_perun_user_attribute_def_opt_perunPeopleId_description();

    @DefaultStringValue("quotaFileSystem")
    String urn_perun_resource_attribute_def_def_quotaFileSystem_name();

    @DefaultStringValue("Filesystem to set quota on")
    String urn_perun_resource_attribute_def_def_quotaFileSystem_description();

    @DefaultStringValue("eduroamIdentities")
    String urn_perun_user_attribute_def_def_eduroamIdentities_name();

    @DefaultStringValue("List of eduroam identities")
    String urn_perun_user_attribute_def_def_eduroamIdentities_description();

    @DefaultStringValue("priorityCoeficient")
    String urn_perun_user_attribute_def_def_priorityCoeficient_name();

    @DefaultStringValue("Priority coeficient based on user's publications")
    String urn_perun_user_attribute_def_def_priorityCoeficient_description();

    @DefaultStringValue("loa")
    String urn_perun_member_attribute_def_def_loa_name();

    @DefaultStringValue("Level of Assurance")
    String urn_perun_member_attribute_def_def_loa_description();

    @DefaultStringValue("unixGID")
    String urn_perun_resource_attribute_def_def_unixGID_name();

    @DefaultStringValue("group GID")
    String urn_perun_resource_attribute_def_def_unixGID_description();

    @DefaultStringValue("unixGroupName")
    String urn_perun_group_resource_attribute_def_def_unixGroupName_name();

    @DefaultStringValue("Unix group name")
    String urn_perun_group_resource_attribute_def_def_unixGroupName_description();

    @DefaultStringValue("unixGID")
    String urn_perun_group_resource_attribute_def_def_unixGID_name();

    @DefaultStringValue("group GID")
    String urn_perun_group_resource_attribute_def_def_unixGID_description();

    @DefaultStringValue("isUnixGroup")
    String urn_perun_group_resource_attribute_def_def_isUnixGroup_name();

    @DefaultStringValue("Does this group represents Unix group?")
    String urn_perun_group_resource_attribute_def_def_isUnixGroup_description();

    @DefaultStringValue("pbsServer")
    String urn_perun_facility_attribute_def_def_pbsServer_name();

    @DefaultStringValue("PBS server wich controls this facility")
    String urn_perun_facility_attribute_def_def_pbsServer_description();

    @DefaultStringValue("unixGID")
    String urn_perun_group_resource_attribute_def_virt_unixGID_name();

    @DefaultStringValue("")
    String urn_perun_group_resource_attribute_def_virt_unixGID_description();

    @DefaultStringValue("defaultUnixGID")
    String urn_perun_user_facility_attribute_def_def_defaultUnixGID_name();

    @DefaultStringValue("")
    String urn_perun_user_facility_attribute_def_def_defaultUnixGID_description();

    @DefaultStringValue("userCertificates")
    String urn_perun_user_attribute_def_def_userCertificates_name();

    @DefaultStringValue("Hash map for all users full certificates")
    String urn_perun_user_attribute_def_def_userCertificates_description();

    @DefaultStringValue("eduPersonAffiliation")
    String urn_perun_member_attribute_def_opt_eduPersonAffiliation_name();

    @DefaultStringValue("User's affliation")
    String urn_perun_member_attribute_def_opt_eduPersonAffiliation_description();

    @DefaultStringValue("researchGroup")
    String urn_perun_member_attribute_def_opt_researchGroup_name();

    @DefaultStringValue("Member's research group")
    String urn_perun_member_attribute_def_opt_researchGroup_description();

    @DefaultStringValue("DN of certificates")
    String urn_perun_user_attribute_def_def_userCertDNs_name();

    @DefaultStringValue("All DNs of user's certificates.")
    String urn_perun_user_attribute_def_def_userCertDNs_description();

    @DefaultStringValue("DN of all certificates")
    String urn_perun_user_attribute_def_virt_userCertDNs_name();

    @DefaultStringValue("All DNs of user's certificates including external identities X509.")
    String urn_perun_user_attribute_def_virt_userCertDNs_description();

    @DefaultStringValue("unixGroupName")
    String urn_perun_resource_attribute_def_virt_unixGroupName_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_virt_unixGroupName_description();

    @DefaultStringValue("unixGID")
    String urn_perun_resource_attribute_def_virt_unixGID_name();

    @DefaultStringValue("")
    String urn_perun_resource_attribute_def_virt_unixGID_description();

    @DefaultStringValue("unixGroupName")
    String urn_perun_group_resource_attribute_def_virt_unixGroupName_name();

    @DefaultStringValue("")
    String urn_perun_group_resource_attribute_def_virt_unixGroupName_description();

    @DefaultStringValue("smb_write")
    String urn_perun_resource_attribute_def_def_smb_write_name();

    @DefaultStringValue("is resource Samba share writeable")
    String urn_perun_resource_attribute_def_def_smb_write_description();

    @DefaultStringValue("sshHostKey")
    String urn_perun_host_attribute_def_def_sshHostKey_name();

    @DefaultStringValue("Host's SSH host key")
    String urn_perun_host_attribute_def_def_sshHostKey_description();

    @DefaultStringValue("shell_passwd-scp")
    String urn_perun_user_facility_attribute_def_def_shell_passwd_scp_name();

    @DefaultStringValue("")
    String urn_perun_user_facility_attribute_def_def_shell_passwd_scp_description();

    @DefaultStringValue("sshPublicKey")
    String urn_perun_user_attribute_def_def_sshPublicKey_name();

    @DefaultStringValue("User's SSH Public Key")
    String urn_perun_user_attribute_def_def_sshPublicKey_description();

    @DefaultStringValue("smb_share_name")
    String urn_perun_resource_attribute_def_def_smb_share_name_name();

    @DefaultStringValue("name of Samba share represented by resource")
    String urn_perun_resource_attribute_def_def_smb_share_name_description();

    @DefaultStringValue("dashboardLink")
    String urn_perun_vo_attribute_def_def_dashboardLink_name();
    
    @DefaultStringValue("Link to the user's dashboard")
    String urn_perun_vo_attribute_def_def_dashboardLink_description();
    
    @DefaultStringValue("userManualsLink")
    String urn_perun_vo_attribute_def_def_userManualsLink_name();
    
    @DefaultStringValue("Link to the user manuals")
    String urn_perun_vo_attribute_def_def_userManualsLink_description();
    
    @DefaultStringValue("afsCell")
    String urn_perun_facility_attribute_def_def_afsCell_name();
    
    @DefaultStringValue("AFS cell name")
    String urn_perun_facility_attribute_def_def_afsCell_description();
    
    @DefaultStringValue("afsPartition")
    String urn_perun_facility_attribute_def_def_afsPartition_name();
    
    @DefaultStringValue("AFS partition")
    String urn_perun_facility_attribute_def_def_afsPartition_description();
    
    @DefaultStringValue("afsServer")
    String urn_perun_facility_attribute_def_def_afsServer_name();
    
    @DefaultStringValue("AFS server")
    String urn_perun_facility_attribute_def_def_afsServer_description();
    
    @DefaultStringValue("afsUserQuota")
    String urn_perun_user_facility_attribute_def_def_afsUserQuota_name();
   
    @DefaultStringValue("AFS user's quota")
    String urn_perun_user_facility_attribute_def_def_afsUserQuota_description();
    
    @DefaultStringValue("afsVolume")
    String urn_perun_resource_attribute_def_def_afsVolume_name();
   
    @DefaultStringValue("AFS top-level volume")
    String urn_perun_resource_attribute_def_def_afsVolume_description();
      
    @DefaultStringValue("afsUsersMountPoint")
    String urn_perun_resource_attribute_def_def_afsUsersMountPoint_name();
   
    @DefaultStringValue("AFS users mountpoint")
    String urn_perun_resource_attribute_def_def_afsUsersMountPoint_description();
     
    @DefaultStringValue("afsDefaultUsersQuota")
    String urn_perun_resource_attribute_def_def_afsDefaultUsersQuota_name();
   
    @DefaultStringValue("Default AFS users quota")
    String urn_perun_resource_attribute_def_def_afsDefaultUsersQuota_description();
    
    
    @DefaultStringValue("afsUsersVolume")
    String urn_perun_resource_attribute_def_def_afsUsersVolume_name();
   
    @DefaultStringValue("Prefix of the AFS volume, where users have theirs directories")
    String urn_perun_resource_attribute_def_def_afsUsersVolume_description();
     
    @DefaultStringValue("afsDefaultRealm")
    String urn_perun_resource_attribute_def_def_afsDefaultUsersRealm_name();
   
    @DefaultStringValue("AFS default users realm (lower case)")
    String urn_perun_resource_attribute_def_def_afsDefaultUsersRealm_description();
     
    //-----new user contact info ---------
    
    @DefaultStringValue("organization")
    String urn_perun_user_attribute_def_def_organization_name();
    
    @DefaultStringValue("User's organization")
    String urn_perun_user_attribute_def_def_organization_description();
    
    @DefaultStringValue("workplace")
    String urn_perun_user_attribute_def_def_workplace_name();
    
    @DefaultStringValue("User's workplace")
    String urn_perun_user_attribute_def_def_workplace_description();

    @DefaultStringValue("address")
    String urn_perun_user_attribute_def_def_address_name();
    
    @DefaultStringValue("User's adress")
    String urn_perun_user_attribute_def_def_address_description();
    
    @DefaultStringValue("researchGroup")
    String urn_perun_user_attribute_def_opt_researchGroup_name();
    
    @DefaultStringValue("Name of the research group where the user work")
    String urn_perun_user_attribute_def_opt_researchGroup_description();
    
    @DefaultStringValue("phone")
    String urn_perun_user_attribute_def_def_phone_name();
    
    @DefaultStringValue("User's phone")
    String urn_perun_user_attribute_def_def_phone_description();

    @DefaultStringValue("preferredLanguage")
    String urn_perun_user_attribute_def_def_preferredLanguage_name();
    
    @DefaultStringValue("User's preferred language")
    String urn_perun_user_attribute_def_def_preferredLanguage_description();
    
    @DefaultStringValue("preferredMail")
    String urn_perun_user_attribute_def_def_preferredMail_name();
    
    @DefaultStringValue("User's preferred mail")
    String urn_perun_user_attribute_def_def_preferredMail_description();
    
    @DefaultStringValue("userSettingsDescription")
    String urn_perun_resource_attribute_def_def_userSettingsDescription_name();
    
    @DefaultStringValue("Description for settings in user detail web page")
    String urn_perun_resource_attribute_def_def_userSettingsDescription_description();
    
    @DefaultStringValue("apacheAuthzFile")
    String urn_perun_resource_attribute_def_def_apacheAuthzFile_name();
    
    @DefaultStringValue("File containing authz entries for Apache")
    String urn_perun_resource_attribute_def_def_apacheAuthzFile_description();

    @DefaultStringValue("Apache SSL authz dir")
    String urn_perun_resource_attribute_def_def_apacheSSLAuthzDir_name();

    @DefaultStringValue("Path to the directory, which will contain list of allowed certificates.")
    String urn_perun_resource_attribute_def_def_apacheSSLAuthzDir_description();
    
    @DefaultStringValue("desc")
    String urn_perun_resource_attribute_def_def_desc_name();
    
    @DefaultStringValue("Short description")
    String urn_perun_resource_attribute_def_def_desc_description();

    @DefaultStringValue("spec")
    String urn_perun_resource_attribute_def_def_spec_name();
    
    @DefaultStringValue("Long description")
    String urn_perun_resource_attribute_def_def_spec_description();
    
    @DefaultStringValue("url")
    String urn_perun_resource_attribute_def_def_url_name();
    
    @DefaultStringValue("URL to hardware description")
    String urn_perun_resource_attribute_def_def_url_description();
    
    @DefaultStringValue("CPUs")
    String urn_perun_host_attribute_def_def_CPUs_name();
    
    @DefaultStringValue("CPU core count")
    String urn_perun_host_attribute_def_def_CPUs_description();
    
    @DefaultStringValue("Reserved")
    String urn_perun_host_attribute_def_def_reserved_name();
    
    @DefaultStringValue("Permanently reserved")
    String urn_perun_host_attribute_def_def_reserved_description();
    
    @DefaultStringValue("frontend")
    String urn_perun_host_attribute_def_def_frontend_name();
    
    @DefaultStringValue("Frontend")
    String urn_perun_host_attribute_def_def_frontend_description();
    
    @DefaultStringValue("applicationURL")
    String urn_perun_vo_attribute_def_def_applicationURL_name();
    
    @DefaultStringValue("Path to the VO application form")
    String urn_perun_vo_attribute_def_def_applicationURL_description();
    
    @DefaultStringValue("contactEmail")
    String urn_perun_vo_attribute_def_def_contactEmail_name();
    
    @DefaultStringValue("VO contact e-mail")
    String urn_perun_vo_attribute_def_def_contactEmail_description();
    
    @DefaultStringValue("membershipExpirationRules")
    String urn_perun_vo_attribute_def_def_membershipExpirationRules_name();
    
    @DefaultStringValue("Rules which defines how the membership is extended.")
    String urn_perun_vo_attribute_def_def_membershipExpirationRules_description();
    
    @DefaultStringValue("Mail footer")
    String urn_perun_vo_attribute_def_def_mailFooter_name();
    
    @DefaultStringValue("Email footer used in mail notifications by tag {mailFooter}. To edit text whithout loose of formatting, please use notification's GUI!!")
    String urn_perun_vo_attribute_def_def_mailFooter_description();
    
    @DefaultStringValue("listOfDestinations")
    String urn_perun_group_attribute_def_def_listOfDestinations_name();
    
    @DefaultStringValue("List of destinations, where the group has some special meaning.")
    String urn_perun_group_attribute_def_def_listOfDestinations_description();
    
    @DefaultStringValue("fromEmail")
    String urn_perun_vo_attribute_def_def_fromEmail_name();
    
    @DefaultStringValue("Email address used as \"From\" in mail notifications.")
    String urn_perun_vo_attribute_def_def_fromEmail_description();
    
    @DefaultStringValue("toEmail")
    String urn_perun_vo_attribute_def_def_toEmail_name();
    
    @DefaultStringValue("Email addresses (of VO administrators) used as \"To\" in mail notifications.")
    String urn_perun_vo_attribute_def_def_toEmail_description();

    @DefaultStringValue("toEmail")
    String urn_perun_group_attribute_def_def_toEmail_name();

    @DefaultStringValue("Email addresses (of Group administrators) used as \"To\" in mail notifications.")
    String urn_perun_group_attribute_def_def_toEmail_description();

    @DefaultStringValue("fromEmail")
    String urn_perun_group_attribute_def_def_fromEmail_name();

    @DefaultStringValue("Email address used as \"From\" in mail notifications.")
    String urn_perun_group_attribute_def_def_fromEmail_description();

    @DefaultStringValue("VO logo's URL")
    String urn_perun_vo_attribute_def_def_voLogoURL_name();
    
    @DefaultStringValue("Full URL to VO's logo image (including \"http://\").")
    String urn_perun_vo_attribute_def_def_voLogoURL_description();
    
    @DefaultStringValue("Publications")
    String urn_perun_user_attribute_def_def_publications_name();
    
    @DefaultStringValue("Number of publications with acknowledgement per resource provider.")
    String urn_perun_user_attribute_def_def_publications_description();
    
    @DefaultStringValue("Jabber")
    String urn_perun_user_attribute_def_def_jabber_name();
    
    @DefaultStringValue("Jabber contact")
    String urn_perun_user_attribute_def_def_jabber_description();
    
    @DefaultStringValue("Spec description")
    String urn_perun_facility_attribute_def_def_spec_name();
    
    @DefaultStringValue("Long description. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_spec_description();
    
    @DefaultStringValue("Description")
    String urn_perun_facility_attribute_def_def_desc_name();
    
    @DefaultStringValue("Short description. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_desc_description();
    
    @DefaultStringValue("HW description URL")
    String urn_perun_facility_attribute_def_def_url_name();
    
    @DefaultStringValue("URL to HW description. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_url_description(); 
    
    @DefaultStringValue("Discs")
    String urn_perun_facility_attribute_def_def_disk_name();
    
    @DefaultStringValue("Description of installed discs. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_disk_description(); 
    
    @DefaultStringValue("Network interfaces")
    String urn_perun_facility_attribute_def_def_network_name();
    
    @DefaultStringValue("Description of network interfaces (Ethernet, Infiniband etc.). Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_network_description();    
    
    @DefaultStringValue("Comment")
    String urn_perun_facility_attribute_def_def_comment_name();
    
    @DefaultStringValue("Comment of hardware description. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_comment_description();   
    
    @DefaultStringValue("Owner")
    String urn_perun_facility_attribute_def_def_owner_name();
    
    @DefaultStringValue("Organization that founded the hardware. Keys for values are languages (eg. cs,en).")
    String urn_perun_facility_attribute_def_def_owner_description();    
    
    @DefaultStringValue("Listing priority")
    String urn_perun_facility_attribute_def_def_listingPriority_name();
    
    @DefaultStringValue("Priority in lists of facilities, ordering higher numbers first.")
    String urn_perun_facility_attribute_def_def_listingPriority_description();     
    
    @DefaultStringValue("Pbsmon server")
    String urn_perun_facility_attribute_def_def_pbsmonServer_name();
    
    @DefaultStringValue("Pbsmon server.")
    String urn_perun_facility_attribute_def_def_pbsmonServer_description();   
    
    @DefaultStringValue("Photo")
    String urn_perun_facility_attribute_def_def_photo_name();
    
    @DefaultStringValue("URL of facility hw photo.")
    String urn_perun_facility_attribute_def_def_photo_description();     
    
    @DefaultStringValue("Thumbnail")
    String urn_perun_facility_attribute_def_def_thumbnail_name();
    
    @DefaultStringValue("URL of facility hw photo's thumbnail.")
    String urn_perun_facility_attribute_def_def_thumbnail_description();      
    
    @DefaultStringValue("CPU")
    String urn_perun_facility_attribute_def_def_cpu_name();
    
    @DefaultStringValue("Description of CPUs (number, cores, vendor, type, frequency).")
    String urn_perun_facility_attribute_def_def_cpu_description();      
    
    @DefaultStringValue("Memory (RAM)")
    String urn_perun_facility_attribute_def_def_memory_name();
    
    @DefaultStringValue("Size of installed RAM.")
    String urn_perun_facility_attribute_def_def_memory_description();
    
    @DefaultStringValue("IP for Flexlm")
    String urn_perun_user_attribute_def_def_IPsForFlexlm_name();
    
    @DefaultStringValue("IP addresses for IPtables on Flexlm server.")
    String urn_perun_user_attribute_def_def_IPsForFlexlm_description();
    
    @DefaultStringValue("Level of assurance")
    String urn_perun_member_attribute_def_virt_loa_name();
    
    @DefaultStringValue("Level of assurance (max. value taken from all userExtSources). 0 = default / 1 = verified by mail / 2 = verified by ID.")
    String urn_perun_member_attribute_def_virt_loa_description();
    
    @DefaultStringValue("Mailing-list exclusion")
    String urn_perun_member_resource_attribute_def_def_optOutMailingList_name();
    
    @DefaultStringValue("By default empty. If any value is set - it excludes member from mailing list represented by Resource (with service \"mailman\").")
    String urn_perun_member_resource_attribute_def_def_optOutMailingList_description();
    
    @DefaultStringValue("Level of assurance by organization (CZ)")
    String urn_perun_user_attribute_def_virt_organizationsWithLoa_cs_name();
    
    @DefaultStringValue("Level of assurance by organization (czech). Value is automatically determined from all user's external identities.")
    String urn_perun_user_attribute_def_virt_organizationsWithLoa_cs_description();
    
    @DefaultStringValue("Level of assurance by organization (EN)")
    String urn_perun_user_attribute_def_virt_organizationsWithLoa_en_name();
    
    @DefaultStringValue("Level of assurance by organization (english). Value is automatically determined from all user's external identities.")
    String urn_perun_user_attribute_def_virt_organizationsWithLoa_en_description();

    @DefaultStringValue("Certificates expiration")
    String urn_perun_user_attribute_def_virt_userCertExpirations_name();

    @DefaultStringValue("Expiration of user certificates.")
    String urn_perun_user_attribute_def_virt_userCertExpirations_description();

    @DefaultStringValue("userPreferredCertDN")
    String urn_perun_user_attribute_def_def_userPreferredCertDN_name();

    @DefaultStringValue("One preferredUser Certificate DN without certificate Authority.")
    String urn_perun_user_attribute_def_def_userPreferredCertDN_description();

    @DefaultStringValue("fsVolume")
    String urn_perun_resource_attribute_def_def_fsVolume_name();

    @DefaultStringValue("Volume on which users's homes dirs are created. (It's not mount point!).")
    String urn_perun_resource_attribute_def_def_fsVolume_description();

    @DefaultStringValue("RT queue name for VO")
    String urn_perun_vo_attribute_def_def_RTVoQueue_name();

    @DefaultStringValue("Name of VO's RT queue.")
    String urn_perun_vo_attribute_def_def_RTVoQueue_description();

    @DefaultStringValue("Public SSH admin key")
    String urn_perun_user_attribute_def_def_sshPublicAdminKey_name();

    @DefaultStringValue("User's SSH public keys used for root access.")
    String urn_perun_user_attribute_def_def_sshPublicAdminKey_description();

    @DefaultStringValue("EPPN")
    String urn_perun_user_attribute_def_virt_eduPersonPrincipalNames_name();

    @DefaultStringValue("Extsource logins from IDP.")
    String urn_perun_user_attribute_def_virt_eduPersonPrincipalNames_description();

    @DefaultStringValue("UID namespace policy")
    String urn_perun_entityless_attribute_def_def_namespace_uid_policy_name();

    @DefaultStringValue("Policy for generating new UID number. recycle - use first available UID, increment - add 1 to last used UID (maximal one).")
    String urn_perun_entityless_attribute_def_def_namespace_uid_policy_description();

    @DefaultStringValue("Cloud platform destination map")
    String urn_perun_facility_attribute_def_def_cloudPlatformDestinationMap_name();

    @DefaultStringValue("Maps cloud platform (opennebula, openstack, ...) to destinations")
    String urn_perun_facility_attribute_def_def_cloudPlatformDestinationMap_description();

    @DefaultStringValue("Shibboleth ExtSources")
    String urn_perun_user_attribute_def_virt_shibbolethExtSources_name();

    @DefaultStringValue("Pairs of IdP identificator and user's EPPN")
    String urn_perun_user_attribute_def_virt_shibbolethExtSources_description();

}