language: java
dist: bionic
jdk:
 - openjdk11
notifications:
  slack:
    secure: CgeySCRL2VzY+/gohsDo5lb9LacQMFB3NjsbQeR57RvuGdemmy3kp9E/3uiHNW0KW0iuIHmcM61BIwhXIeQrSER5+pBqvDgzsc+EFEzott8QedZm0ezGEDhX5nqemmqwUJH8jEYZx/IRpza0pwz3p0tygIJhIZtlJVD7KfyXCJk=
