#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Assigns service to the resource. Resource and service are required fields.
--------------------------------------
Available options:
 --serviceId   | -s service id
 --serviceName | -S service name
 --resourceId  | -r resource id
 --batch       | -b batch
 --help        | -h prints this help
 
};
}

my ($resourceId, $serviceId, $serviceName, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "resourceId|r=i" => \$resourceId,
 "serviceId|s=i" => \$serviceId,
 "serviceName|S=s" => \$serviceName) || die help(); 

# Check options
unless (defined($resourceId)) { die "ERROR: resourceId is required \n";}
unless (defined($serviceId) or defined($serviceName)) { die "ERROR: serviceId or serviceName is required \n";}

my $agent = Perun::Agent->new();

unless($serviceId) {
    my $servicesAgent = $agent->getServicesAgent;
    my $service = $servicesAgent->getServiceByName(name => $serviceName);
    $serviceId=$service->getId;
}

my $resourcesAgent = $agent->getResourcesAgent;

$resourcesAgent->assignService(resource => $resourceId, service => $serviceId);

printMessage("Service Id:$serviceId successfully assigned to the resource Id:$resourceId", $batch);
