#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Change a member's status. Member id is required.
--------------------------------------
Available options:
 --memberId   | -m member id
 --newStatus  | -s new status
 --batch      | -b batch
 --help       | -h prints this help
 
};
}

our $batch;
my ($memberId,$status);
GetOptions ("help|h" => sub { print help(); exit 0;} ,
 "batch|b" => \$batch,
 "newStatus|s=s" => \$status,
 "memberId|m=i" => \$memberId) || die help(); 

# Check options
unless (defined($memberId)) { die "ERROR: memberId is required \n";}
unless (defined($status)) { die "ERROR: newStatus status is required \n";}

my $agent = Perun::Agent->new();
my $membersAgent = $agent->getMembersAgent;

$membersAgent->setStatus(member => $memberId, status => $status);

printMessage("Staus of member Id:$memberId successfully set to $status", $batch);
