#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Creates a services package. ServicesPackage name is required field.
--------------------------------------
Available options:
 --packageName        | -P package name
 --packageDescription | -d description
 --batch              | -b batch
 --help               | -h prints this help
 
};
}

my ($packageName, $dsc, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "packageName|P=s" => \$packageName,"packageDescription|d=s" => \$dsc) || die help(); 

# Check options
unless (defined($packageName)) { die "ERROR: packageName is required \n";}

my $agent = Perun::Agent->new();
my $servicesAgent = $agent->getServicesAgent;

my $package = Perun::beans::ServicesPackage->new;
$package->setName($packageName);
$package->setDescription($dsc);

$package = $servicesAgent->createServicesPackage(servicesPackage => $package);

printMessage("Service Package Id:".$package->getId." successfully created", $batch);
