#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Deletes a securityTeam. SecurityTeam id is required field.
	--------------------------------------
	Available options:
        --securityTeamId   | -s Id of deleted securityTeam
	--batch            | -b batch
	--help             | -h prints this help

	};
}

my ($securityTeamId, $securityTeamName, $desc, $batch);
GetOptions ("help|h"     => sub {
		print help();
		exit 0;
	}, "batch|b"         => \$batch,
	"securityTeamId|s=i" => \$securityTeamId || die help());

# Check options
unless (defined($securityTeamId)) { die "ERROR: securityTeamId is required \n";}

my $agent = Perun::Agent->new();
my $securityTeamsAgent = $agent->getSecurityTeamsAgent;

$securityTeamsAgent->deleteSecurityTeam( securityTeam => $securityTeamId );

printMessage("SecurityTeam Id:".$securityTeamId." successfully deleted", $batch);
