#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Deletes a service package. ServicesPackage name or id is required field.
--------------------------------------
Available options:
 --packageName | -P package name
 --packageId   | -p packageId
 --batch       | -b batch
 --help        | -h prints this help
 
};
}

my ($packageName, $packageId, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "packageName|P=s" => \$packageName,
 "packageId|p=i" => \$packageId) || die help(); 

# Check options
unless (defined($packageName) or defined($packageId)) { die "ERROR: packageName or packageId is required \n";}

my $agent = Perun::Agent->new();
my $servicesAgent = $agent->getServicesAgent;

unless ($packageId) {
    my $package = $servicesAgent->getServicesPackageByName(name => $packageName);
    $packageId=$package->getId;
}

$servicesAgent->deleteServicesPackage(servicesPackage => $packageId);

printMessage("Service Package Id:".$packageId." deleted", $batch);
