#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Text::ASCIITable;
use Perun::Agent;
use Perun::Common qw(printMessage tableToPrint);

sub help {
return qq{
Find user by member id.
------------------------
Available options:
 --memberId | -m member id
 --batch    | -b batch
 --help     | -h prints this help

};
}

my ($memberId, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "memberId|m=i" => \$memberId)|| die help();

# Check options
unless (defined($memberId)) { die "ERROR: memberId is required \n";}

my $agent = Perun::Agent->new();
my $usersAgent = $agent->getUsersAgent;

my $user = $usersAgent->getUserByMember(member => $memberId);

#output
my $table = Text::ASCIITable->new();
$table->setCols('ID','Name');
my $name = $user->getFirstName . " " . ($user->getMiddleName ? $user->getMiddleName . " " : "" ) . $user->getLastName;
$table->addRow($user->getId, $name);
print tableToPrint($table, $batch);

