#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Text::ASCIITable;
use Perun::Agent;
use Perun::Common qw(printMessage printTable getSortingFunction);

sub help {
	return qq{
	Prints list of publications.
	------------------------------
	Available options:
	--orderById    | -i  order by identifier of publication
	--orderByName  | -n  order by title of publication
	--batch        | -b  batch
	--help         | -h  prints this help
	};
}

our $batch;
my ($sortingFunction);

GetOptions("help|h" => sub {
		print help;
		exit 0;
	},
	"orderById|i"   => sub { $sortingFunction = getSortingFunction("getId") },
	"orderByName|n" => sub { $sortingFunction = getSortingFunction("getTitle", 1) },
	"batch|b"       => \$batch) || die help;

my $agent = Perun::Agent->new();
my $cabinetAgent = $agent->getCabinetAgent;

#options check
unless (defined $sortingFunction) { $sortingFunction = getSortingFunction("getTitle", 1); }

my @publications = $cabinetAgent->findPublicationsByGUIFilter();
unless (@publications) {
	printMessage "No publications found", $batch;
	exit 0;
}

#output
printTable($sortingFunction, @publications);
