#!/usr/bin/perl

use strict;
use Getopt::Long qw(:config no_ignore_case);
use Text::ASCIITable;
use Perun::Agent;
use Perun::Common qw(printMessage tableToPrint getSortingFunction); 

sub help {
return qq{
Prints list of Principal Roles
---------------------------------
Available options:
 --batch       | -b batch
 --help        | -h prints this help
 
};
}

my ($batch);
GetOptions("help|h" => sub { print help; exit 0;} , 
           "batch|b" => \$batch) || die help;

my $agent = Perun::Agent->new();
my $authzResolverAgent = $agent->getAuthzResolverAgent;

my @roles = $authzResolverAgent->getPrincipalRoleNames;
unless(@roles) { printMessage "No Roles found", $batch; exit 0;}

#output
my $table = Text::ASCIITable->new();
$table->setCols('Role Name');

foreach my $role (@roles) {
  $table->addRow($role);
}

print tableToPrint($table, $batch);
