#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage);

sub help {
	return qq{
	Removes user from BlackList SecurityTeam. User id and SecurityTeam are required fields.
	------------------------------------
	Available options:
	--securityTeamId | -s SecurityTeam id
	--userId         | -u user id
	--batch          | -b batch
	--help           | -h prints this help

	};
}

my ($securityTeamId, $userId, $desc, $batch);
GetOptions ("help|h"     => sub {
		print help();
		exit 0;
	}, "batch|b"         => \$batch,
	"securityTeamId|s=i" => \$securityTeamId,
	"userId|u=i"         => \$userId || die help());

# Check options
unless (defined($userId)) { die "ERROR: userId is required \n";}
unless (defined($securityTeamId)) {die "ERROR: securityTeamId is required\n";}

my $agent = Perun::Agent->new();
my $securityTeamsAgent = $agent->getSecurityTeamsAgent;

$securityTeamsAgent->removeUserFromBlacklist( securityTeam => $securityTeamId, user => $userId );

printMessage("User Id:$userId successfully removed from BlackList of SecurityTeam $securityTeamId", $batch);

