#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Removes all resource-member attributes. Resource id and member id are required.
--------------------------------------
Available options:
 --resourceId   | -r resource id 
 --memberId     | -m member id
 --batch        | -b batch
 --help         | -h prints this help

};
}

my ($resourceId, $memberId, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "resourceId|r=i" => \$resourceId, "memberId|m=i" => \$memberId ) || die help(); 

# Check options
unless (defined($resourceId)) { die "ERROR: resourceId is required \n";}
unless (defined($memberId)) { die "ERROR: memberId is required \n";}

my $agent = Perun::Agent->new();
my $attributesAgent = $agent->getAttributesAgent;

$attributesAgent->removeAllAttributes(resource => $resourceId, member => $memberId);
    
printMessage("All attributes removed from the resource Id:$resourceId and member Id:$memberId", $batch);
