#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);
use Perun::Agent;
use Perun::Common qw(printMessage); 

sub help {
return qq{
Removes all attributes from the facility. Facility id or name is required.
-------------------------------------------------
Available options:
 --facilityId   | -f facility id 
 --facilityName | -F facility name
 --facilityType | -t facility type
 --batch        | -b batch
 --help         | -h prints this help

};
}

my ($facilityId, $facilityName, $facilityType, $batch);
GetOptions ("help|h" => sub { print help(); exit 0;} ,"batch|b" => \$batch,
 "facilityId|f=i" => \$facilityId, 
 "facilityType|t=s" => \$facilityType, 
 "facilityName|F=s" => \$facilityName) || die help(); 

# Check options
unless (defined($facilityId) or (defined($facilityName) and defined($facilityType))) { die "ERROR: facilityId or facilityName+facilityType is required \n";}

my $agent = Perun::Agent->new();

unless($facilityId) {
    my $facilitiesAgent = $agent->getFacilitiesAgent;
    my $facility = $facilitiesAgent->getFacilityByName(name => $facilityName, type => $facilityType);
    $facilityId=$facility->getId;
}

my $attributesAgent = $agent->getAttributesAgent;

$attributesAgent->removeAllAttributes(facility => $facilityId);
    
printMessage("All attributes removed from the facility Id:$facilityId", $batch);
