#!/bin/bash
#
# Example pre-file for LDAP service providing authz information.
# For production use remove "example-" prefix for file and fill the values.
#
# LDAP_LOGIN=[login]
# LDAP_PASSWORD=[password]
# LDAP_URL=[LDAP server location with optional ":port" part]
# LDAP_FILTER_USERS=[filter for query in standard LDAP syntax used to read current state of ldap (users)]
# LDAP_FILTER_GROUPS=[filter for query in standard LDAP syntax used to read current state of ldap (groups)]
#
LDAP_LOGIN=
LDAP_PASSWORD=
LDAP_URL=
LDAP_FILTER_USERS="(objectclass=*)"
LDAP_FILTER_GROUPS="(objectclass=*)"