package cz.metacentrum.perun.cabinet.dao.mybatis;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cz.metacentrum.perun.cabinet.model.Author;
import cz.metacentrum.perun.cabinet.model.Authorship;

public interface AuthorshipMapper {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int countByExample(AuthorshipExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int deleteByExample(AuthorshipExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	Integer insert(Authorship record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int insertSelective(Authorship record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	List<Authorship> selectByExample(AuthorshipExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	Authorship selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int updateByExampleSelective(@Param("record") Authorship record, @Param("example") AuthorshipExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int updateByExample(@Param("record") Authorship record, @Param("example") AuthorshipExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int updateByPrimaryKeySelective(Authorship record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table REPORT
	 *
	 * @mbggenerated Fri Nov 04 19:37:17 CET 2011
	 */
	int updateByPrimaryKey(Authorship record);

	List<Authorship> findByFilter(Authorship filter);

	List<Authorship> findByParams(Map<String, Object> params);

	List<Integer> selectUniqueAuthorsIds();

	Author findAuthorByUserId(@Param("userId") Integer userId);

	List<Author> findAuthorsByPublicationId(@Param("pubId") Integer publicationId);

	List<Author> findAllAuthors();

}
