package cz.metacentrum.perun.cabinet.dao.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cz.metacentrum.perun.cabinet.model.Thanks;
import cz.metacentrum.perun.cabinet.model.ThanksForGUI;

public interface ThanksMapper {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int countByExample(ThanksExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int deleteByExample(ThanksExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int insert(Thanks record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int insertSelective(Thanks record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	List<Thanks> selectByExample(ThanksExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	Thanks selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int updateByExampleSelective(@Param("record") Thanks record, @Param("example") ThanksExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int updateByExample(@Param("record") Thanks record, @Param("example") ThanksExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int updateByPrimaryKeySelective(Thanks record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table THANKS
	 *
	 * @mbggenerated Fri Nov 04 19:38:27 CET 2011
	 */
	int updateByPrimaryKey(Thanks record);

	List<Thanks> findThanksByFilter(Thanks t);

	List<ThanksForGUI> selectRichByExample(ThanksExample t);

	List<ThanksForGUI> selectAllRichByUserId(Integer user);

}
