#!/bin/bash
#
# Example pre-file for LDAP service providing authz information.
#
# LDAP_LOGIN=[login]
# LDAP_PASSWORD=[password]
# LDAP_URL=[LDAP server location with optional ":port" part]
#
LDAP_LOGIN=
LDAP_PASSWORD=
LDAP_URL=
