#!/bin/sh
# By default setting qoutas are disabled (0), to enable set next variable to 1
#QUOTA_ENABLED=0

# Set custom setquota program
#SET_QUOTA_PROGRAM="/usr/lpp/mmfs/bin/mmsetquota"

# Parameters template for custom set quota program
# Available variables: $U_HOME_MNT_POINT $U_LOGNAME $U_UID $SOFT_QUOTA_DATA $HARD_QUOTA_DATA $SOFT_QUOTA_FILES $HARD_QUOTA_FILES $QUOTA_FS
# *_DATA are in kB
# NOTE: value must be in single quotes
#SET_QUOTA_TEMPLATE='--user ${U_UID} --disk_softquota ${SOFT_QUOTA_DATA}k --disk_hardquota ${HARD_QUOTA_DATA}k ${U_HOME_MNT_POINT}'
