package cz.metacentrum.perun.core.bl;


import cz.metacentrum.perun.core.api.OidcConfig;
import cz.metacentrum.perun.core.api.exceptions.OidcConfigFileNotExistsException;
import cz.metacentrum.perun.core.api.exceptions.OidcConfigNotExistsException;

/**
 * ConfigManager serves to manage configuration files.
 *
 * @author David Flor <493294@mail.muni.cz>
 */
public interface ConfigManagerBl {

  /**
   * Returns Oidc Configuration for this Perun instance (to be used for CLI communication).
   *
   * @param requestUrl url of request
   * @return oidcConfig
   * @throws OidcConfigNotExistsException     when configuration under such name doesn't exist
   * @throws OidcConfigFileNotExistsException when configuration file for oidc configs doesn't exist.
   */
  OidcConfig getPerunOidcConfig(String requestUrl)
      throws OidcConfigNotExistsException, OidcConfigFileNotExistsException;

  /**
   * Reloads the configuration of brandings and their respective apps (see perun-apps-config.yml)
   */
  void reloadAppsConfig();

  /**
   * Checks whether spool files generated by the engine should be archived
   */
  boolean isArchiveSpoolEnabled();
}
