#!/bin/sh
# Set custom setquota program
#SET_QUOTA_PROGRAM="/usr/lpp/mmfs/bin/mmsetquota"

# Parameters template for custom set quota program
# Available variables: $GID $SOFT_QUOTA_DATA $HARD_QUOTA_DATA $SOFT_QUOTA_FILES $HARD_QUOTA_FILES $QUOTA_FS
# *_DATA are in kB
# NOTE: value must be in single quotes
#SET_QUOTA_TEMPLATE='--group ${GID} --disk_softquota ${SOFT_QUOTA_DATA}k --disk_hardquota ${HARD_QUOTA_DATA}k ${U_HOME_MNT_POINT}'
